apiVersion: apps/v1
kind: Deployment
metadata:
  name: video
  namespace: demo
spec:
  replicas: 1
  minReadySeconds: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: video
  template:
    metadata:
      name: video
      labels:
        app: video
    spec:
      containers:
        - name: video
          image: jormin/video:latest
          ports:
            - containerPort: 80
              protocol: TCP
          readinessProbe:
            periodSeconds: 60
            httpGet:
              path: /
              port: 80

---

apiVersion: v1
kind: Service
metadata:
  name: video
  namespace: demo
spec:
  type: NodePort
  selector:
    app: video
  # 端口
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31802
